In [1]:
import torch
from torch import nn

In [29]:
a = torch.Tensor([[[1, 1],
                   [1, 0]],
                  [[1, 0.5],
                   [1, 0]]])

b = torch.Tensor([[[1, 1],
                   [0, 0]],
                  [[1, 0],
                   [1, 0]]])


In [35]:
torch.sum(a, dim=1), torch.sum(a, dim=2)

(tensor([[2.0000, 1.0000],
         [2.0000, 0.5000]]),
 tensor([[2.0000, 1.0000],
         [1.5000, 1.0000]]))

In [38]:
c = torch.sum(torch.mul(a, b), dim=2)
c

tensor([[2., 0.],
        [1., 1.]])

In [42]:
d = - torch.log(c)
d

tensor([[-0.6931,     inf],
        [-0.0000, -0.0000]])

In [43]:
e = torch.sum(b, dim=2)
e

tensor([[2., 0.],
        [1., 1.]])

In [46]:
f = torch.mul(d, e)
f

tensor([[-1.3863,     nan],
        [-0.0000, -0.0000]])

In [48]:
g = (1 / e.shape[0]) * f
g

tensor([[-0.6931,     nan],
        [-0.0000, -0.0000]])

In [49]:
torch.sum(g)

tensor(nan)