In [1]:
import numpy as np
import pandas as pd
from typing import List, Tuple
from sklearn.ensemble import RandomForestClassifier

In [47]:
def fwls(X_mf, X_meta):

    R_list = []
    for row in np.arange(X_meta.shape[0]):
        M = X_mf[row].reshape(X_mf.shape[1], 1)
        P = X_meta[row].reshape(X_meta.shape[1], 1)
        F = np.multiply(M, P.T)
        r = F.shape[0]
        c = F.shape[1]
        f = F.reshape(r * c)
        R_list.append(f)
    return np.vstack(R_list)


In [57]:
M = np.array([[1,2], [1,2], [1,2]])

In [53]:
M = np.zeros((3, 2)) + 1
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
P = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
P

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [58]:
fwls(M, P)

array([[ 1,  2,  3,  4,  5,  6,  2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  4,  5,  6,  2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  4,  5,  6,  2,  4,  6,  8, 10, 12]])

In [56]:
fwls(P, M)

array([[1., 1., 2., 2., 3., 3., 4., 4., 5., 5., 6., 6.],
       [1., 1., 2., 2., 3., 3., 4., 4., 5., 5., 6., 6.],
       [1., 1., 2., 2., 3., 3., 4., 4., 5., 5., 6., 6.]])

In [61]:
np.arange(10).argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.load("../data/clfs_output/split_10_with_val/webkb/10_folds/gbm/0/probas.npy", allow_pickle=True).shape

(823, 7)

In [10]:
np.load("../data/clfs_output/split_10_with_val/webkb/10_folds/gbm/0/train_probas.npy", allow_pickle=True).shape

(6638, 7)

In [9]:
np.load("../data/labels/split_10_with_val/webkb/0/train.npy", allow_pickle=True).shape

(6638,)

In [8]:
np.load("../data/labels/split_10_with_val/webkb/0/test.npy", allow_pickle=True).shape

(823,)

In [1]:
from IPython.core.display import display, HTML
import random
rawdata = '''the USS Ronald Reagan - an aircraft carrier docked in Japan - during his tour of the region, vowing to "defeat any attack and meet any use of conventional or nuclear weapons with an overwhelming and effective American response".
North Korea and the US have ratcheted up tensions in recent weeks and the movement of the strike group had raised the question of a pre-emptive strike by the US.
On Wednesday, Mr Pence described the country as the "most dangerous and urgent threat to peace and security" in the Asia-Pacific.'''
words = rawdata.split()
word_num = len(words)
attention = [(x+1.) / word_num for x in range(word_num)]  # estabelecendo pesos aleatórios só para exemplificar: pode ser usado a importancia de feature do modelo
random.seed(42)
random.shuffle(attention)
heatmap_source = ""

for i in range (len(words)):
        heatmap_source =  heatmap_source +  "<span title=\"attention: "+str(attention[i])+"\" style=\"background-color: rgb(255,0,0, "+str(attention[i]) +  ")\"> " + words[i] + "  </span>"
display(HTML(heatmap_source))