In [1]:
import pickle
import numpy as np
import pandas as pd
import jsonlines
import os

In [55]:
from cProfile import label
from itertools import product

DATASETS = ['20ng', 'acm', 'webkb', 'reut']

for dset, fold in product(DATASETS, range(10)):

    
    ids = pickle.load( open(f'../data/datasets/{dset}/splits/split_10_with_val.pkl', 'rb') ) 
    jp = f"/home/claudiovaliense/projetos/kaggle/{dset}_bert{fold}.json"
    fdj = jsonlines.open(jp)
    docs = []
    for line in fdj:
        docs.append([line['id'], line['bert'], line['label']])
        
    dest_dir = f"../data/reps/split_10_with_val/bert_base/fine_tuning/{dset}/{fold}"
    os.makedirs(dest_dir, exist_ok=True)
    
    
    X = pd.DataFrame(docs, columns=['id', 'bert', 'label'])
    x_train = np.array(X.query(f"id == {ids['train_idxs'][fold]}").bert.values.tolist())
    x_val = np.array(X.query(f"id == {ids['val_idxs'][fold]}").bert.values.tolist())
    x_test = np.array(X.query(f"id == {ids['test_idxs'][fold]}").bert.values.tolist())

    train_path = f"{dest_dir}/train"
    np.save(train_path, x_train)

    val_path = f"{dest_dir}/val"
    np.save(val_path, x_val)

    test_path = f"{dest_dir}/test"
    np.save(test_path, x_test)


    label_dir = f"../data/labels/split_10_with_val/{dset}/{fold}/"
    os.makedirs(label_dir, exist_ok=True)

    y_train = np.array(X.query(f"id == {ids['train_idxs'][fold]}").label.values.tolist())
    y_val = np.array(X.query(f"id == {ids['val_idxs'][fold]}").label.values.tolist())
    y_test = np.array(X.query(f"id == {ids['test_idxs'][fold]}").label.values.tolist())

    train_path = f"{label_dir}/train"
    np.save(train_path, y_train)

    val_path = f"{label_dir}/val"
    np.save(val_path, y_val)

    test_path = f"{label_dir}/test"
    np.save(test_path, y_test)




In [10]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.shuffle(X)
X

array([2, 5, 0, 4, 8, 7, 9, 1, 6, 3])

In [12]:
X.argsort()

array([2, 7, 0, 9, 3, 1, 8, 5, 4, 6])

In [13]:
X[X.argsort()]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.load("../data/clfs_output/split_10_with_val/webkb/10_folds/lr/0/train_probas.npy").shape

(6638, 7)

In [15]:
np.load("../data/clfs_output/split_10_with_val/webkb/10_folds/lr/0/probas.npy").shape

(823, 7)

In [3]:
a = np.array([])